/* 
 * Copyright (c) 2020 OnePacs LLC, All rights reserved
 * November 06, 2020 by Jay Liu
 */

export const ActionTypes = {
    LOAD_USER_PREFERENCES_REQUESTED: 'USER_PREFERENCES::LOAD_REQUESTED',
    LOAD_USER_PREFERENCES_SUCCESS: 'USER_PREFERENCES::LOAD_SUCCESS',
    LOAD_USER_PREFERENCES_FAILED: 'USER_PREFERENCES::LOAD_FAILED',
    SAVE_USER_PREFERENCES_REQUESTED: 'USER_PREFERENCES::SAVE_REQUESTED',
    SAVE_USER_PREFERENCES_SUCCESS: 'USER_PREFERENCES::SAVE_SUCCESS',
    SAVE_USER_PREFERENCES_FAILED: 'USER_PREFERENCES::SAVE_FAILED',
};

export const Status = {
    INITIAL: 'initial',
    LOADING: 'loading',
    SAVING: 'saving',
    SUCCESS: 'success',
    FAILED: 'failed',
};
